[package]
name = "next-build-test"
version = "0.1.0"
description = "TBD"
license = "MPL-2.0"
edition = "2021"
autobenches = false

[lints]
workspace = true

[dependencies]
next-api = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }
turbopack-binding = { workspace = true, features = [
    "__turbo_tasks",
    "__turbo_tasks_memory",
    "__turbo_tasks_env",
    "__turbo_tasks_fs",
    "__turbo_tasks_memory",
    "__turbo_tasks_malloc",
    "__turbopack",
    "__turbopack_nodejs",
    "__turbopack_core",
    "__turbopack_browser",
    "__turbopack_ecmascript",
    "__turbopack_ecmascript_runtime",
    "__turbopack_env",
    "__turbopack_node",
] }
turbo-tasks = { workspace = true }
rand = { workspace = true, features = ["small_rng"] }
num_cpus = "1.16.0"
tokio-stream = "0.1.15"
tracing = "0.1"
tracing-subscriber = "0.3"
futures-util = "0.3.30"

# Enable specific tls features per-target.
[target.'cfg(all(target_os = "windows", target_arch = "aarch64"))'.dependencies]
next-core = { workspace = true, features = ["native-tls"] }

[target.'cfg(not(any(all(target_os = "windows", target_arch = "aarch64"), target_arch="wasm32")))'.dependencies]
next-core = { workspace = true, features = ["rustls-tls"] }

[build-dependencies]
turbopack-binding = { workspace = true, features = ["__turbo_tasks_build"] }
